FORMAT: 1A

# Mercatus

Mercatus is a simple API allowing consumers to view organizations and projects.

# Group Organizations
Resources related to organizations

## Organization Collection [/orgs]
Get organization list or create new org.

### List all organizations [GET]
Lists all organizations

+ Response 200 (application/json)
[{"id": 1,"orgDesc": "Main Org","orgName": "Mercatus"}]

### API to create organization [POST]
You may create your own organization
+ id (long) - The id
+ orgDesc (string) - Org description
+ orgName (string) - Org name

+ Request (application/json)
{"id": 2,"orgDesc": "Workfront enabled","orgName": "ENEL"}

+ Response 200 (application/json)
{"id": 2,"orgDesc": "Workfront enabled","orgName": "ENEL"}

## Organization Collection [/orgs/name]
Gets list of organization names and ids

### List all organizations [GET]

+ Response 200 (application/json)
[{"id": 1, "orgName": "Mercatus"}]

## Get organization [/orgs/{id}]
Get individual org

### Get Org by id [GET]
Get org by id

+ Response 200 (application/json)
{"id": 1,"orgDesc": "Main Org","orgName": "Mercatus"}

### Update org [PUT]
Update org

+ Request 201 (application/json)
{"id": 1,"orgDesc": "Main Org","orgName": "Mercatus"}

# Group Projects
Resources related projects

## Project collection [/projects]
Get list of projects

### Get list of projects [GET]
Get list of all projects

+ Response 200 (application/json)
[{"id":1, "orgId":1, "name":proj1}]
